name: gestion_parc_informatique
description: Application de gestion de parc informatique avec Flutter et Firebase
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  badges: ^2.0.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  provider: ^6.1.1
  flutter_form_builder: ^9.1.1
  material_design_icons_flutter: ^7.0.7296
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.3.1
  http: ^1.1.0
  flutter_svg: ^2.0.17
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.svg"
  adaptive_icon_background: "#E8EAF6"
  adaptive_icon_foreground: "assets/icons/app_icon.svg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.svg
          style: normal
          weight: 400
  uses-material-design: true