// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

///[FirebaseOptions]
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmUuUNCuhmq8tZFxoN0GNBzPnV4iP7qgo',
    appId: '1:888572217070:web:2e8674407ca9e7e98955ff',
    messagingSenderId: '888572217070',
    projectId: 'mondodev2',
    authDomain: 'mondodev2.firebaseapp.com',
    storageBucket: 'mondodev2.firebasestorage.app',
    measurementId: 'G-NPVNGNMQMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpPPjrNffXTRwEmOf-goojdWi4yJVkXIw',
    appId: '1:888572217070:android:1c3179556fd7c7118955ff',
    messagingSenderId: '888572217070',
    projectId: 'mondodev2',
    storageBucket: 'mondodev2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_0471Kfwp61lHaTSS93b9exmyl3UV7W0',
    appId: '1:888572217070:ios:944db68629c8408c8955ff',
    messagingSenderId: '888572217070',
    projectId: 'mondodev2',
    storageBucket: 'mondodev2.firebasestorage.app',
    iosBundleId: 'com.mondo.dev.testulti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmUuUNCuhmq8tZFxoN0GNBzPnV4iP7qgo',
    appId: '1:888572217070:web:8c8dbc2a8862ef288955ff',
    messagingSenderId: '888572217070',
    projectId: 'mondodev2',
    authDomain: 'mondodev2.firebaseapp.com',
    storageBucket: 'mondodev2.firebasestorage.app',
    measurementId: 'G-QDNQP0Z3HV',
  );

}