// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

///[FirebaseOptions]
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvw6dxgP5Oju-54j0x3GUVyV2QsX-zuzU',
    appId: '1:564591051312:web:f033ca142c9b74094a23f5',
    messagingSenderId: '564591051312',
    projectId: 'gestion-parc-informatiqu-c7d69',
    authDomain: 'gestion-parc-informatiqu-c7d69.firebaseapp.com',
    storageBucket: 'gestion-parc-informatiqu-c7d69.firebasestorage.app',
    measurementId: 'G-HYP9PCHSGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbcNH-qQ2HOB0Pim_6QhIRqnVaRpQcUcA',
    appId: '1:564591051312:android:399a95613ecc1c084a23f5',
    messagingSenderId: '564591051312',
    projectId: 'gestion-parc-informatiqu-c7d69',
    storageBucket: 'gestion-parc-informatiqu-c7d69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCPr1pwaLIsbipNP1NjLNHhdzcjAsN-2k',
    appId: '1:564591051312:ios:291782065fedfcd64a23f5',
    messagingSenderId: '564591051312',
    projectId: 'gestion-parc-informatiqu-c7d69',
    storageBucket: 'gestion-parc-informatiqu-c7d69.firebasestorage.app',
    iosBundleId: 'com.mondo.dev.testulti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvw6dxgP5Oju-54j0x3GUVyV2QsX-zuzU',
    appId: '1:564591051312:web:fcbb296d471976e64a23f5',
    messagingSenderId: '564591051312',
    projectId: 'gestion-parc-informatiqu-c7d69',
    authDomain: 'gestion-parc-informatiqu-c7d69.firebaseapp.com',
    storageBucket: 'gestion-parc-informatiqu-c7d69.firebasestorage.app',
    measurementId: 'G-K5JTR3RPQB',
  );

}